'use strict';
const $=id=>document.getElementById(id),fields=['scope','division','school','conductor','work','query','composer','event','family','stage','award','ensemble','size','from','to','status'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalized=s=>String(s??'').normalize('NFKC').replace(/\s+/g,'').toLowerCase();
let db,schools,conductors,works,events,sources,view='school',layout='timeline',page=1,filtered=[];
const names={school:'学校別',conductor:'指揮者別',work:'曲目別',event:'大会別',ensemble:'編成別',stats:'統計'};
const maps={school:()=>schools,conductor:()=>conductors,work:()=>works,event:()=>events};
function link(type,id,label){return id?`<button class="link" data-link="${type}" data-id="${esc(id)}">${esc(label)}</button>`:'<span class="muted">未確認</span>';}
function medal(r){return `<span class="badge ${r.award==='金賞'?'gold':r.award==='銀賞'?'silver':r.award==='銅賞'?'bronze':''}">${esc(r.award||'未確認')}</span>${r.recommendation?'<span class="badge rep">代表</span>':''}`;}
function piece(r){return r.pieces.map(p=>`<small>${r.performed===false?'予定曲（辞退・欠場） · ':r.performed===null?'実演未確認 · ':''}${esc(p.role)}</small>${p.workId?link('work',p.workId,works.get(p.workId).title):esc(p.raw)+'（曲名未確認）'}`).join('<br>')||'<span class="muted">曲目未確認</span>';}
function option(id,entries,first='すべて'){const val=$(id).value;$(id).innerHTML=`<option value="">${first}</option>`+entries.map(([v,t])=>`<option value="${esc(v)}">${esc(t)}</option>`).join('');$(id).value=val;}
function resetValues(){fields.filter(f=>f!=='scope').forEach(f=>$(f).value='');page=1;}
function route(v,type,id){resetValues();view=v;layout=v==='school'||v==='conductor'?'timeline':'table';if(type)$(type).value=id;else if(v==='school')$('school').value=defaultSchool();if(type==='school'||type==='conductor'||type==='event'){const x=maps[type]().get(id);const lv=type==='conductor'?schools.get(x.schoolId).level:x.level;if(lv!==$('scope').value){$('scope').value=lv;setupScope();$(type).value=id}}render();$('content').scrollIntoView({behavior:'smooth',block:'start'});}
function storeState(){const p=new URLSearchParams({view,layout});fields.forEach(f=>{if($(f).value)p.set(f,$(f).value)});history.replaceState(null,'','#'+p);}
function readState(){const p=new URLSearchParams(location.hash.slice(1));if(names[p.get('view')])view=p.get('view');if(['timeline','table'].includes(p.get('layout')))layout=p.get('layout');resetValues();$('scope').value=p.get('scope')==='高等学校'?'高等学校':'中学校';setupScope();fields.forEach(f=>{if(p.has(f))$(f).value=p.get(f)});if(!location.hash)$('school').value=defaultSchool();}
function filterRecords(){const f=Object.fromEntries(fields.map(f=>[f,$(f).value]));return db.performances.filter(r=>{
 const e=events.get(r.eventId),c=conductors.get(r.conductorId),s=schools.get(r.schoolId),ws=r.pieces.map(p=>works.get(p.workId)).filter(Boolean);
 if(r.level!==f.scope||f.division&&r.division!==f.division)return false;
 if(f.school&&r.schoolId!==f.school&&!(s.memberSchoolIds||[]).includes(f.school)||f.conductor&&r.conductorId!==f.conductor||f.work&&!r.pieces.some(p=>p.workId===f.work)||f.event&&r.eventId!==f.event)return false;
 if(f.from&&r.year<+f.from||f.to&&r.year>+f.to||f.family&&e.family!==f.family||f.stage&&e.stage!==f.stage||f.award&&r.award!==f.award||f.ensemble&&r.ensembleCategory!==f.ensemble||f.size&&String(r.size)!==f.size||f.status&&r.status!==f.status)return false;
 if(f.composer&&!ws.some(w=>normalized(w.composer).includes(normalized(f.composer))))return false;
 const hay=[s.name,s.officialName,...s.aliases,r.division,c?.name,e.name,e.label,r.ensemble,r.award,...r.pieces.map(p=>p.raw),...ws.map(w=>[w.title,w.composer,w.arranger].join(' '))].join(' ');
 return !f.query||normalized(hay).includes(normalized(f.query));
 });}
function title(){if(view==='school'&&$('school').value)return schools.get($('school').value)?.name||names[view];if(view==='conductor'&&$('conductor').value)return conductors.get($('conductor').value)?.name||names[view];if(view==='work'&&$('work').value)return works.get($('work').value)?.title||names[view];if(view==='event'&&$('event').value){const e=events.get($('event').value);return `${e.year}年度 ${e.label}`}return {school:'学校から、歴史をたどる',conductor:'演奏を導いた先生たち',work:'あの曲は、どこで演奏された？',event:'大会と年度から探す',ensemble:'小さな編成、それぞれの響き',stats:'記録から見える、長野の吹奏楽'}[view];}
function metrics(rs){return `<div class="metrics">${[[rs.length,'大会記録'],[new Set(rs.map(r=>r.year)).size,'年度分'],[rs.filter(r=>r.award==='金賞').length,'金賞の記録'],[rs.filter(r=>r.recommendation).length,'代表推薦の記録']].map(([n,t])=>`<div class="metric"><strong>${n.toLocaleString()}</strong><span>${t}</span></div>`).join('')}</div>`;}
function context(){let out='';if(view==='school'&&$('school').value){const s=schools.get($('school').value);out=`<p class="muted">${esc(s.officialName)} · ${esc(s.municipality||'所在地未確認')}</p>`;if(s.isJoint)out+='<p class="joint-note">合同参加の記録です。単独校の記録と区別しています。</p>';if(s.memberSchoolIds?.length)out+='<p>合同参加校：'+s.memberSchoolIds.map(id=>link('school',id,schools.get(id).name)).join(' · ')+'</p>';if(s.relations.length)out+=`<p>学校の変遷：${s.relations.map(rel=>link('school',rel.schoolId,schools.get(rel.schoolId).name)).join(' · ')}（統合の詳細・実施日は追加確認が必要）</p>`;out+=s.nameHistory.map(h=>`<p>${esc(h.name)} ${esc(h.from)}〜${esc(h.to)}</p>`).join('');out+=`<p class="muted">学校情報の出典：${s.sourceIds.map(id=>sourceLink(id)).join(' · ')}。履歴が空欄の場合、名称変更がないことを意味しません。</p>`;}
 if(view==='conductor'){out+='<p class="muted">以下は大会で指揮したことを確認できる年度です。勤務・在籍期間や異動年は未確認です。</p>';if($('conductor').value){const c=conductors.get($('conductor').value);out+=`<p>${link('school',c.schoolId,schools.get(c.schoolId).name)}での記録 · ${esc(c.identityStatus)}</p>`;const same=db.conductors.filter(x=>x.id!==c.id&&x.normalizedName===c.normalizedName);if(same.length)out+=`<p class="muted">他校の同じ表記（同一人物か未確認）：${same.map(x=>link('conductor',x.id,schools.get(x.schoolId).name+'／'+x.name)).join(' · ')}</p>`;}}
 if(view==='work'&&$('work').value){const w=works.get($('work').value);out+=`<p>作曲：${esc(w.composer||'未確認')} · 編曲：${esc(w.arranger||'未確認')}</p><p class="muted">抜粋・編曲が異なる記録は別曲目として管理しています。同じ原曲は曲名検索で探せます。</p>`;}
 if(view==='event'&&$('event').value){const e=events.get($('event').value);out+=`<p>${esc(e.name)} · ${esc(e.stage)} · ${esc(e.date||'開催日未確認')} · ${esc(e.venue||'会場未確認')}</p>`;}
 if(view==='ensemble')out+='<p class="muted">編成と人数を組み合わせて検索できます。人数は資料の編成表記から確認した値です。未記載の人数は集計しません。</p>';
 return out;}
function sourceLink(id){const s=sources.get(id);return s?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.publisher)}：${esc(s.title)}</a>`:'';}
function table(rs){return `<div class="table-wrap"><table><caption class="muted">年度・大会ごとの演奏記録。名称を押すと関連記録を表示します。</caption><thead><tr><th>年度</th><th>学校</th><th>大会</th><th>指揮者</th><th>演奏曲</th><th>編成</th><th>結果</th><th>出典・詳細</th></tr></thead><tbody>${rs.map(r=>{const e=events.get(r.eventId);return `<tr><th>${r.year}</th><td>${link('school',r.schoolId,schools.get(r.schoolId).name)}</td><td>${link('event',e.id,e.name)}<small>${esc(e.stage)} · ${esc(e.label)}</small></td><td>${link('conductor',r.conductorId,conductors.get(r.conductorId)?.name)}</td><td class="song">${piece(r)}</td><td>${esc(r.ensemble||'未確認')}<small>${r.size?r.size+'人':''}</small></td><td>${medal(r)}</td><td><button class="link" data-detail="${r.id}">詳細・出典</button><small>${esc(r.status)}</small></td></tr>`}).join('')}</tbody></table></div>`;}
function timeline(rs){const years=[...new Set(rs.map(r=>r.year))].sort((a,b)=>b-a);return `<div class="timeline">${years.map(y=>`<div class="year-block"><div class="year-label">${y}<small class="muted">年度</small></div><div class="cards">${rs.filter(r=>r.year===y).map(r=>{const e=events.get(r.eventId);return `<article class="card"><div class="card-top"><h3>${link('event',e.id,e.name)}<small class="muted"> · ${esc(e.stage)}</small></h3><div>${medal(r)}</div></div><p>${link('school',r.schoolId,schools.get(r.schoolId).name)} · ${esc(r.ensemble||'編成未確認')}</p><p class="song">${piece(r)}</p><p>指揮：${link('conductor',r.conductorId,conductors.get(r.conductorId)?.name)}</p><p class="muted">${esc(e.date||'開催日未確認')} · ${esc(r.status)}</p><button class="link" data-detail="${r.id}">記録の詳細と出典 ↗</button></article>`}).join('')}</div></div>`).join('')}</div>`;}
function countBy(rs,key){const m=new Map();rs.forEach(r=>{const k=key(r);if(k!==null&&k!==undefined)m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>b[1]-a[1]);}
function chart(label,entries,limit=12){const rows=entries.slice(0,limit),max=Math.max(1,...rows.map(x=>x[1]));return `<section class="chart"><h3>${esc(label)}</h3>${rows.map(([t,n,type,id])=>`<div class="bar-row"><div>${type?link(type,id,t):esc(t)}</div><div class="bar-track" aria-hidden="true"><div class="bar" style="width:${n/max*100}%"></div></div><strong>${n}</strong></div>`).join('')||'<p class="muted">対象記録なし（参加・受賞状況は未確認）</p>'}${entries.length>limit?`<details><summary>全${entries.length}項目の数値を見る</summary><div class="table-wrap"><table><thead><tr><th>項目</th><th>件数</th></tr></thead><tbody>${entries.map(([t,n])=>`<tr><td>${esc(t)}</td><td>${n}</td></tr>`).join('')}</tbody></table></div></details>`:''}</section>`;}
function awardChart(rs){const ys=[...new Set(rs.map(r=>r.year))].sort((a,b)=>a-b),max=Math.max(1,...ys.map(y=>rs.filter(r=>r.year===y&&['金賞','銀賞','銅賞'].includes(r.award)).length));return `<section class="chart"><h3>年度別の金・銀・銅賞</h3><div class="legend"><span class="badge gold">金賞</span><span class="badge silver">銀賞</span><span class="badge bronze">銅賞</span></div>${ys.map(y=>{const counts=['金賞','銀賞','銅賞'].map(a=>rs.filter(r=>r.year===y&&r.award===a).length);return `<div class="bar-row"><span>${y}年度</span><div class="bar-track" aria-hidden="true">${counts.map((n,i)=>`<div class="bar ${['gold','silver','bronze'][i]}" style="width:${n/max*100}%"></div>`).join('')}</div><strong>${counts.reduce((a,b)=>a+b,0)}</strong></div><span class="muted">金${counts[0]} / 銀${counts[1]} / 銅${counts[2]}</span>`}).join('')}<p class="muted">大会段階ごとに1記録。空白年度は未確認。金・銀・銅以外の賞はこのグラフから除きます。</p></section>`;}
function stats(rs){rs=rs.filter(r=>r.performed===true);const schoolAward=db.schools.map(s=>[s.name,rs.filter(r=>r.schoolId===s.id&&r.award==='金賞').length,'school',s.id]).filter(x=>x[1]).sort((a,b)=>b[1]-a[1]);const reps=countBy(rs.filter(r=>r.recommendation),r=>r.schoolId).map(([id,n])=>[schools.get(id).name,n,'school',id]);const teachers=countBy(rs.filter(r=>r.conductorId&&r.award==='金賞'),r=>r.conductorId).map(([id,n])=>[conductors.get(id).name+'／'+schools.get(conductors.get(id).schoolId).name,n,'conductor',id]);const songs=countBy(rs.flatMap(r=>r.pieces.filter(p=>p.workId)),p=>p.workId).map(([id,n])=>[works.get(id).title,n,'work',id]);const annual=[...new Set(rs.map(r=>r.year))].sort((a,b)=>a-b).map(y=>[y+'年度',new Set(rs.filter(r=>r.year===y).map(r=>r.schoolId)).size]);const ensembles=countBy(rs.filter(r=>events.get(r.eventId).family==='ankon'),r=>r.ensembleCategory||'編成未確認');return `<p class="muted">現在の検索条件を反映しています。辞退・欠場や実演未確認の記録は統計から除外します。合同団体は別項目です。演奏回数は大会段階ごとの記録数で、同じ演奏の地区・県出場は別々に数えます。推薦回数と上位大会の実出場回数は異なります。</p><div class="chart-grid">${awardChart(rs)}${chart('学校別の金賞記録数',schoolAward)}${chart('学校別の代表推薦記録数',reps)}${chart('指揮者別の金賞記録数',teachers)}${chart('曲目別の演奏記録数',songs)}${chart('年度別の登録学校・合同団体数',annual,30)}${chart('アンサンブル編成別の記録数',ensembles)}</div>`;}
function browse(rs){const kind={school:'school',conductor:'conductor',work:'work',event:'event'}[view];if(!kind||$(kind).value)return '';let ent=countBy(kind==='work'?rs.flatMap(r=>r.pieces.filter(p=>p.workId)):rs,r=>kind==='work'?r.workId:r[kind+'Id']);if(kind==='school')ent=db.schools.filter(s=>s.level===$('scope').value).map(s=>[s.id,rs.filter(r=>r.schoolId===s.id).length]);const m=maps[kind]();return `<details><summary>${names[view]}の索引（${ent.length}項目）</summary><div class="table-wrap"><table><thead><tr><th>名称</th><th>登録記録数</th></tr></thead><tbody>${ent.map(([id,n])=>{const x=m.get(id);return x?`<tr><td>${link(kind,id,kind==='work'?x.title:kind==='event'?x.year+'年度 '+x.label:x.name)}${kind==='conductor'?'<small>'+esc(schools.get(x.schoolId).name)+'</small>':''}</td><td>${n}</td></tr>`:''}).join('')}</tbody></table></div></details>`;}
function render(){filtered=filterRecords();if(view==='ensemble'){filtered=filtered.filter(r=>events.get(r.eventId).family==='ankon')}const rs=filtered;const limit=60,total=Math.max(1,Math.ceil(rs.length/limit));page=Math.min(page,total);const subset=rs.slice((page-1)*limit,page*limit);document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));const tools=view==='stats'?'':`<div class="view-tools"><button data-layout="timeline" class="${layout==='timeline'?'active':''}">年表</button><button data-layout="table" class="${layout==='table'?'active':''}">表</button><button id="csv">CSVを保存</button></div>`;
 let body=`<div class="content-head"><div><p class="eyebrow">${names[view]} / EXPLORE THE ARCHIVE</p><h2>${esc(title())}</h2>${context()}</div>${tools}</div>${metrics(rs)}${browse(rs)}`;
 if($('from').value&&$('to').value&&+$('from').value>+$('to').value)body+='<p class="empty">開始年度は終了年度以前にしてください。</p>';
 else if(!rs.length)body+='<p class="empty">この条件の登録記録はありません。未調査・未確認の記録があるため、参加なし・受賞なしとは判断できません。条件をリセットすると、全体から探せます。</p>';
 else if(view==='stats')body+=stats(rs);
 else{if(view==='school')body+=`<details><summary>成績の推移をグラフで見る</summary><div class="chart-grid">${awardChart(rs)}</div></details>`;body+=(layout==='timeline'?timeline(subset):table(subset));body+=`<div class="pager"><button data-page="${page-1}" ${page===1?'disabled':''}>前へ</button><span>${(page-1)*limit+1}–${Math.min(page*limit,rs.length)} / ${rs.length}件</span><button data-page="${page+1}" ${page===total?'disabled':''}>次へ</button></div>`;}
 $('content').innerHTML=body;$('content').setAttribute('aria-busy','false');storeState();}
function detail(id){const r=db.performances.find(r=>r.id===id);if(!r)return;const e=events.get(r.eventId);$('detail-body').innerHTML=`<p class="eyebrow">PERFORMANCE RECORD</p><h2>${r.year}年度 ${esc(schools.get(r.schoolId).name)}</h2><dl><dt>大会</dt><dd>${link('event',e.id,e.name)} · ${esc(e.stage)}<br>${esc(e.label)}</dd><dt>開催日</dt><dd>${esc(e.date||'未確認')}</dd><dt>会場</dt><dd>${esc(e.venue||'未確認')}</dd><dt>学校</dt><dd>${link('school',r.schoolId,schools.get(r.schoolId).officialName)}</dd><dt>指揮者</dt><dd>${link('conductor',r.conductorId,conductors.get(r.conductorId)?.name)}</dd><dt>部門</dt><dd>${esc(r.level)}</dd><dt>A・B等の編成</dt><dd>${esc(r.division?r.division+(r.division.length===1?'編成':''):'未確認・対象外')}<small> · 原表記：${esc(r.divisionRaw||'未確認')}</small></dd><dt>編成・人数</dt><dd>${esc(r.ensemble||'未確認')} · ${r.size?r.size+'人':'人数未確認'}</dd><dt>演奏曲</dt><dd>${piece(r)}${r.pieces.filter(p=>p.workId).map(p=>{const w=works.get(p.workId);return `<p class="muted">作曲：${esc(w.composer||'未確認')}／編曲：${esc(w.arranger||'未確認')}</p>`}).join('')}</dd><dt>参加状況</dt><dd>${esc(r.participationStatus)}</dd><dt>結果</dt><dd>${medal(r)}</dd><dt>推薦</dt><dd>${r.recommendation?'代表推薦を確認':'資料に代表表示なし。推薦・進出の詳細は未確認。'}<br>原表記：${esc(r.recommendationNote)}</dd><dt>確認状況</dt><dd>${esc(r.status)}（賞・学校・記載曲目は公式表を確認。空白項目は未確認。）</dd></dl><p class="muted">${esc(r.note)}</p><h3>出典</h3><ul>${r.sourceIds.map(id=>`<li>${sourceLink(id)}<small> · 確認日 ${esc(sources.get(id).checkedAt)}</small></li>`).join('')}</ul><details><summary>公式資料の原表記</summary><pre>${esc(r.rawRow.join('\n'))}</pre></details>`;$('detail').showModal();}
function downloadCSV(){const rows=[['年度','対象部門','コンクール編成','学校','大会','段階','指揮者','曲目','編成','人数','賞','代表推薦','確認状況','参加状況','出典URL'],...filtered.map(r=>{const e=events.get(r.eventId);return [r.year,r.level,r.division||'未確認・対象外',schools.get(r.schoolId).officialName,e.name,e.stage,conductors.get(r.conductorId)?.name||'未確認',r.pieces.map(p=>p.workId?works.get(p.workId).title:p.raw+'（課題曲番号）').join(' / '),r.ensemble||'未確認',r.size||'未確認',r.award,r.recommendation?'確認済み':'未確認',r.status,r.participationStatus,r.sourceIds.map(id=>sources.get(id).url).join(' ')]})];const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='suwa-band-history.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

function defaultSchool(){return $('scope').value==='中学校'?db.defaultSchoolId:db.schools.find(s=>s.level==='高等学校'&&s.officialName==='諏訪清陵高等学校')?.id||db.schools.find(s=>s.level==='高等学校').id;}
function renderCoverage(){const lv=$('scope').value;$('coverage').innerHTML=`<p class="muted">${esc(lv)}部門の登録状況</p><div class="table-wrap coverage"><table><thead><tr><th>年度</th><th>吹奏楽（記録数）</th><th>アンサンブル・重奏（記録数）</th></tr></thead><tbody>${Array.from({length:27},(_,i)=>2026-i).map(y=>`<tr><th>${y}</th>${['contest','ankon'].map(f=>{const c=db.coverage.find(c=>c.year===y&&c.family===f&&c.level===lv);return `<td>${esc(c.status)} · ${c.recordCount}件<small>${esc(c.note)}</small></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`;}
function setupScope(){const lv=$('scope').value;const ss=db.schools.filter(s=>s.level===lv),cs=db.conductors.filter(c=>schools.get(c.schoolId).level===lv),es=db.events.filter(e=>e.level===lv);const ws=new Set(db.performances.filter(r=>r.level===lv).flatMap(r=>r.pieces.map(p=>p.workId).filter(Boolean)));option('school',ss.map(s=>[s.id,(s.municipality||'所在地未確認')+' · '+s.name]));option('conductor',cs.sort((a,b)=>a.name.localeCompare(b.name,'ja')).map(c=>[c.id,c.name+'／'+schools.get(c.schoolId).name]));option('event',es.sort((a,b)=>b.year-a.year).map(e=>[e.id,e.year+'年度 '+e.name+' · '+e.label]));option('work',db.works.filter(w=>ws.has(w.id)).sort((a,b)=>a.title.localeCompare(b.title,'ja')).map(w=>[w.id,w.title+(w.composer?'／'+w.composer:'')]));renderCoverage();}

async function init(){try{const response=await fetch('data.json');if(!response.ok)throw Error('HTTP '+response.status);db=await response.json();[schools,conductors,works,events,sources]=['schools','conductors','works','events','sources'].map(k=>new Map(db[k].map(x=>[x.id,x])));option('school',db.schools.map(s=>[s.id,s.municipality+' · '+s.name]));option('conductor',db.conductors.slice().sort((a,b)=>a.name.localeCompare(b.name,'ja')).map(c=>[c.id,c.name+'／'+schools.get(c.schoolId).name]));option('work',db.works.slice().sort((a,b)=>a.title.localeCompare(b.title,'ja')).map(w=>[w.id,w.title+(w.composer?'／'+w.composer:'')]));option('event',db.events.slice().sort((a,b)=>b.year-a.year).map(e=>[e.id,e.year+'年度 '+e.name+' · '+e.label]));option('award',[...new Set(db.performances.map(r=>r.award))].sort().map(a=>[a,a]));option('ensemble',['木管','金管','打楽器','クラリネット','サクソフォーン','フルート','混合','その他'].map(a=>[a,a]));option('division',[...new Set(db.performances.map(r=>r.division).filter(Boolean))].sort().map(n=>[n,n.length===1?n+'編成 / '+n+'部門':n]));option('size',[...new Set(db.performances.map(r=>r.size).filter(Boolean))].sort((a,b)=>a-b).map(n=>[n,n+'人']));$('overview').innerHTML=[[db.schools.filter(s=>!s.isJoint).length,'学校名を登録'],[db.performances.length,'大会記録'],[db.works.length,'曲目'],[db.sources.length,'出典']].map(([n,t])=>`<span><strong>${n.toLocaleString()}</strong>${t}</span>`).join('');$('data-meta').textContent=`データ確認日：${db.updatedAt}。諏訪地区の中学校と長野県全体の高校を対象に、2009〜2026年度を中心に登録。合同団体は別項目で登録。2000〜2008年度の旧システム資料、東海・全国大会、学校沿革・在籍情報は追加調査が必要です。`;renderCoverage();
 fields.forEach(id=>$(id).addEventListener(['query','composer','from','to'].includes(id)?'input':'change',()=>{page=1;if(id==='scope'){resetValues();setupScope();$('school').value=defaultSchool()}render()}));$('reset').addEventListener('click',()=>{resetValues();render()});$('tabs').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)route(b.dataset.view)});document.addEventListener('click',e=>{const b=e.target.closest('[data-link],[data-detail],[data-layout],[data-page],#csv');if(!b)return;if(b.dataset.link){if($('detail').open)$('detail').close();route(b.dataset.link,b.dataset.link,b.dataset.id)}else if(b.dataset.detail)detail(b.dataset.detail);else if(b.dataset.layout){layout=b.dataset.layout;render()}else if(b.dataset.page){page=+b.dataset.page;render();$('content').scrollIntoView({block:'start'})}else downloadCSV()});$('close-detail').addEventListener('click',()=>$('detail').close());window.addEventListener('hashchange',()=>{readState();page=1;render()});readState();render();}catch(error){$('content').setAttribute('aria-busy','false');$('content').innerHTML='<p class="empty">データを読み込めませんでした。通信を確認してページを再読み込みしてください。ローカルで確認する場合はHTTPサーバーで開いてください。</p>';console.error(error)}}
init();
